#!/usr/bin/env bash
#A script that displays he content of he current directory
#In a list format where only the part of the name after
#the first dash is displayed

filelist=$(ls)

for i in $filelist; do
  echo "$i" | cut -d '-' -f2
done
