#!/usr/bin/env bash
# A script that displays all the active IPv4 IPs on the mechine
# ip command is more morden and ifconfig is deprecated on many Linux distributions
# ip -4 -o addr show | awk '{print $4}' | cut -d'/' -f1
ifconfig | grep 'inet addr:' | cut -d: -f2 | cut -d" " -f1
